
import __ASTRO_IMAGE_IMPORT_1MhJcc from "./browser-rendering.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftest1%2Ftest1.md";
import __ASTRO_IMAGE_IMPORT_ZVLKtG from "./browser-rendering.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_1hfnfd from "./critical-rendering-path.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_2snkuP from "./dom.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_2gCWYb from "./render-tree.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_Hff9K from "./layout.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_Z1Y487S from "./painting.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_Z1Cqi0l from "./update-dom.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_Z1s9dMI from "./update-layout-painting.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_Za2QBR from "./all-updates.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_Z1Or5rA from "./render-phase.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_ZkLycU from "./commit-phase.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_Z2iupAn from "./react-rendering.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
import __ASTRO_IMAGE_IMPORT_Z1a4LO from "./dffing.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md";
export default new Map([["./browser-rendering.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftest1%2Ftest1.md", __ASTRO_IMAGE_IMPORT_1MhJcc], ["./browser-rendering.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_ZVLKtG], ["./critical-rendering-path.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_1hfnfd], ["./dom.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_2snkuP], ["./render-tree.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_2gCWYb], ["./layout.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_Hff9K], ["./painting.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_Z1Y487S], ["./update-dom.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_Z1Cqi0l], ["./update-layout-painting.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_Z1s9dMI], ["./all-updates.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_Za2QBR], ["./render-phase.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_Z1Or5rA], ["./commit-phase.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_ZkLycU], ["./react-rendering.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_Z2iupAn], ["./dffing.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbrowser-react-rendering%2Fbrowser-react-rendering.md", __ASTRO_IMAGE_IMPORT_Z1a4LO]]);
		